import { domAnimation, LazyMotion, m } from 'framer-motion'
import { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <LazyMotion features={domAnimation} >
    <m.div 
      initial={{
        opacity: 0,
        y: -50
      }}
      animate={{
        opacity: 1,
        y: 0
      }}
      exit={{
        opacity: 0,
        y: 50
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Next.js Typescript TailwindCSS Framer-motion Starter</h1>
      </main>
    </m.div>
    </LazyMotion>
  )
}

export default Home